[package]
name = "rust-descs"
version = "0.1.0"
edition = "2018"

build = "build.rs"

[lib]
name = "rust_descs"
crate-type = ["cdylib"]

[dependencies]
unicode-segmentation = "1.6.0"
strsim = "0.9.3"

[dependencies.pyo3]
version = "0.11.1"
features = ["extension-module"]
